# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('dataEHoraDeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDeInicio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('senha', models.CharField(max_length=50, verbose_name='senha')),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Usuario'),
        ),
        migrations.AddField(
            model_name='projetousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Usuario'),
        ),
    ]
